### ISSUE TITLE
Input the details on top and ran the script and it did not work

### ISSUE THREAD

**Issue by RtikTwitch** [impshum/sticky-twitch-stream-thing#1]
I put in all the details: (obviously where I have hidden I have the actual ID's)

```
twitch_client_id = 'hidden'
target_user = 'uberhaxornova'

client_id = 'NovaLiveScript'
client_secret = 'hidden'
reddit_user = 'uberhaxornovabot'
reddit_pass = 'password'
target_sub = 'r/uberhaxornova'
```

Just so I'm clear on all of this:
twitch_client_id: The ID of the application from Twitch's side
target_user: ? Stream name I assumed but I haven't messed with Twitch API 
client_id: Reddit script name?
client_secret: Reddit secret ID
reddit_user: Bot username
reddit_pass: Bot password
target_sub: Target subreddit

Is there anything I'm missing? All I did was download it to my PC, unzip it, and then edit it in IDLE and then tried to run it. When he tried to stream today nothing happened.

**Comment by impshum** [comment]
client_id is the id under the name. In the example below the id will be AStIlLi6XlTkJA.

Also... I didn't use IDLE or any other tools, just Atom to write and a standard terminal to run. If you're going to let it run 24/7 just use a terminal/prompt.

<img width="217" alt="Screenshot 2019-09-07 at 08 33 26" src="https://user-images.githubusercontent.com/3229127/64471491-36e0d480-d14a-11e9-9922-aad72596116e.png">

**Comment by RtikTwitch** [comment]
So now the only thing I'm missing is the modules (requests and PRAW is all I need I'm assuming). I have no experience downloading modules, and after spending about 2 hours trying I'm ready to tear my hair out. Any chance you could send me the modules or explain how to download them?

**Comment by impshum** [comment]
Instructions step 1

`pip install -r requirements.txt`

**Comment by RtikTwitch** [comment]
Nvm figured it out.
Ran the module and got this:
```
== RESTART: C:\Users\arcti\Desktop\sticky-twitch-stream-thing-master\run.py ==
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\praw\models\listing\generator.py", line 52, in __next__
    self._next_batch()
  File "F:\Python\lib\site-packages\praw\models\listing\generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "F:\Python\lib\site-packages\praw\reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "F:\Python\lib\site-packages\praw\reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "F:\Python\lib\site-packages\prawcore\sessions.py", line 185, in request
    params=params, url=url)
  File "F:\Python\lib\site-packages\prawcore\sessions.py", line 116, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "F:\Python\lib\site-packages\prawcore\sessions.py", line 101, in _make_request
    params=params)
  File "F:\Python\lib\site-packages\prawcore\rate_limit.py", line 35, in call
    kwargs['headers'] = set_header_callback()
  File "F:\Python\lib\site-packages\prawcore\sessions.py", line 145, in _set_header_callback
    self._authorizer.refresh()
  File "F:\Python\lib\site-packages\prawcore\auth.py", line 328, in refresh
    password=self._password)
  File "F:\Python\lib\site-packages\prawcore\auth.py", line 142, in _request_token
    payload.get('error_description'))
prawcore.exceptions.OAuthException: invalid_grant error processing request
```

**Comment by impshum** [comment]
And did you make a Twitch app and add the token?

**Comment by RtikTwitch** [comment]
Yup
![Twitch](https://user-images.githubusercontent.com/55009785/64495647-2754af00-d262-11e9-9bcf-84f384adf11d.png)

**Comment by impshum** [comment]
That's good.

It looks like your reddit details are not correct.

**Comment by RtikTwitch** [comment]
Checked the reddit details, all of them are correct, still have the same error message. Copy pasted the user and pass to get into the bot account and it worked. copy pasted the ID's and they matched.

**Comment by RtikTwitch** [comment]
Ok.... After some googling found out that I'm supposed to be using my account and not the bot's account for the script. now I get this error:
```
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\praw\models\listing\generator.py", line 52, in __next__
    self._next_batch()
  File "F:\Python\lib\site-packages\praw\models\listing\generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "F:\Python\lib\site-packages\praw\reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "F:\Python\lib\site-packages\praw\reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "F:\Python\lib\site-packages\prawcore\sessions.py", line 185, in request
    params=params, url=url)
  File "F:\Python\lib\site-packages\prawcore\sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.BadRequest: received 400 HTTP response
```

**Comment by impshum** [comment]
That's the same praw error as before. You're clearly doing something very wrong.

**Comment by RtikTwitch** [comment]
Started over. Ran it on Atom and a terminal and got all the reddit crap sorted out. Now I have this error:
![atom_2019-09-14_11-14-32](https://user-images.githubusercontent.com/55009785/64910891-f1d81780-d6e0-11e9-984e-64857c984b9e.png)

**Comment by impshum** [comment]
OK, I've got the error myself. Twitch updated the API again.

`{'error': 'Gone', 'status': 410, 'message': "It's time to kick ass and serve v3... and I'm all outta v3. See https://dev.twitch.tv/docs"}`

I've updated the script but not tested yet (bad me).

**Comment by RtikTwitch** [comment]
Did some research. Twitch is on v5 if your code is on v3 still idk what will need to change. I messed with it to no avail. (I have very little experience with Python)

I did a clean download of the code input all the required arguments and got this:
![atom_2019-09-17_21-44-06](https://user-images.githubusercontent.com/55009785/65103721-b1a0bf80-d994-11e9-85e9-733946689cf5.png)

**Comment by impshum** [comment]
> I've updated the script but not tested yet (bad me).

**Comment by impshum** [comment]
OK, I'm now writing this blind as my auth has packed in for some reason.

I've added ```return data['data']['id']``` to the get_id function.

Try again.

**Comment by RtikTwitch** [comment]
```
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    main()
  File "run.py", line 85, in main
    get_stream()
  File "run.py", line 55, in get_stream
    target_user_id = get_id()
  File "run.py", line 51, in get_id
    return data['data']['id']
KeyError: 'data'   
```
Sorry for so much hassle. I don't want to stress you out over this lol. This can wait, just let me know whenever you make any progress, is there like a follow button for projects?
